### ISSUE TITLE
访友录 | 林深时见璐

### ISSUE THREAD

**Issue by linwhitehat** [linwhitehat/linwhitehat.github.io#1]
https://linwhitehat.github.io/guest/

不乱于心，不困于情。 深谋若谷，深交若水，
不畏将来，不念过往。 深明大义，深悉小节，
如此，安好。 已然，静舒。
善宽以怀，善感以恩， 勿感于时，勿伤于怀，
善博以浪，善精以业， 勿耽美色，勿沉虚妄，
这般，最佳。 从此，进取。
无愧于天，无愧于地，
无怍于人，无惧于鬼，
这样，人生。

《不宠无惊过一生》

**Comment by linwhitehat** [comment]
沙发

**Comment by Lucy-Lin** [comment]
老婆大人在此💑

**Comment by linwhitehat** [comment]
博客迁移完成

**Comment by linwhitehat** [comment]
测试

**Comment by linwhitehat** [comment]
> 老婆大人在此💑

老公巨人在此😘

**Comment by linwhitehat** [comment]
欢迎访友互加友链，申请友链可按以下格式留言：
网站名称：林深时见璐
网站地址：https://linwhitehat.github.io/
网站标志：https://linwhitehat.github.io/icons/rabbit512.png
网站描述：Wonderful U - AGA

**Comment by linwhitehat** [comment]
> ## 关于pwa的知识，我大概摸索了一个多星期，百度上搜不到最新的内容，竟然在github上搜到了，先来感谢下大佬。另外，这还让我猝不及防地吃了口狗粮，哈哈
> # 祝99~

谢谢~欢迎交流

**Comment by SuperPung** [comment]
已经添加贵站友链！

```
名称：SuperPung
网址：https://blog.superpung.xyz
标志：https://gravatar.loli.net/avatar/cdd8da7ae0aaeb08b93d66ded8973570?s=512
描述：Follow Your Heart

**Comment by linwhitehat** [comment]
> 已经添加贵站友链！
> 
> ```
> 名称：SuperPung
> 网址：https://blog.superpung.xyz
> 标志：https://gravatar.loli.net/avatar/cdd8da7ae0aaeb08b93d66ded8973570?s=512
> 描述：Follow Your Heart
> ```

已加友链，欢迎交流

**Comment by leirock** [comment]
已添加贵站友联。我的博客信息如下：

```
名称：醉里挑灯赏猫
地址：https://blog.dlzhang.com
标志：https://sdn.geekzu.org/avatar/cc763511474fe24ffcc80257fb7cb970?size=512
描述：靡革匪因 靡故匪新
```

**Comment by silentteller** [comment]
hi,打扰了，看了您这篇https://www.jianshu.com/p/d21b0f799219，想问下fork后，rename之后访问提示404，这个我需要怎么修改。

**Comment by linwhitehat** [comment]
> hi,打扰了，看了您这篇[https://www.jianshu.com/p/d21b0f799219，想问下fork后，rename之后访问提示404，这个我需要怎么修改。](https://www.jianshu.com/p/d21b0f799219%EF%BC%8C%E6%83%B3%E9%97%AE%E4%B8%8Bfork%E5%90%8E%EF%BC%8Crename%E4%B9%8B%E5%90%8E%E8%AE%BF%E9%97%AE%E6%8F%90%E7%A4%BA404%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%88%91%E9%9C%80%E8%A6%81%E6%80%8E%E4%B9%88%E4%BF%AE%E6%94%B9%E3%80%82)

这个就是基于GitHub本身的博客页面，你检查是不是域名设置不正确

**Comment by SuperPung** [comment]
> > 已经添加贵站友链！
> > ```
> > 名称：SuperPung
> > 网址：https://blog.superpung.xyz
> > 标志：https://gravatar.loli.net/avatar/cdd8da7ae0aaeb08b93d66ded8973570?s=512
> > 描述：Follow Your Heart
> > ```
> 
> 已加友链，欢迎交流

博主您好，我的网址更新为 [https://blog.superpung.cn](https://blog.superpung.cn)，劳烦更改一下~
